query($id: ID!){ 
  product(identifier: {field: id, value: $id}){
    priceRange {
      sellingPrice {
        highPrice
      }
    }
    linkText
    items {
      name
      images {
        imageUrl
      }
    }
  }
}